### ISSUE TITLE
Versione 2016 ar7000 smart

### ISSUE THREAD

**Issue by wifi75** [cicciovo/homebridge-samsung-airconditioner#16]
Ciao Ciccio, sto cercando di trovare una solzuione a questi clima smart che come ben sai hanno un app orribile.
Ho letto che questo script può funzionare, ma non so se le versione ar7000 smart vanno su porta 8888 o altro. sai darmi info in merito?

**Comment by Giuse1977** [comment]
Very same problem, ar7000 working on port 2878, trying to authenticate with openssl s_client -connect ipaddress:port -cert pathtocert and using the certificate from https://github.com/SebuZet/samsungrac I always get an error related to the self-signed certificate.
What should I do?
@wifi75 prova con un port scanner. Il mio è uguale al tuo, ma pare che nella stessa serie potrebbero esserci firmware diversi

**Comment by Giuse1977** [comment]
wtf..It simply works even if I got certificate error!After getting error, I sent the token request and powered up my d7000 and the token was displayed! Thanks!
