### ISSUE TITLE
Cannot connect AC

### ISSUE THREAD

**Issue by gcherem** [cicciovo/homebridge-samsung-airconditioner#24]
Hi, I have a brand new samsung [AR12NSPXBWKNAZ](https://www.samsung.com/br/air-conditioners/wall-mount/ar12nspxbwknaz/), and I didn't find both well known ports 2878 or 8888.

A full slow port scan found only the following ports:

49153 / UDP / open filtered
49154 / UDP / open
49155 / UDP / open

Any idea?

**Comment by mindvisionro** [comment]
Any update?

**Comment by cicciovo** [comment]
Sorry, no idea
