### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by szeldavid** [cicciovo/homebridge-samsung-airconditioner#5]
Hello,

I cannot even install the plugin, I get the attached text which never ends...
<img width="868" alt="kepernyofoto 2018-05-28 - 20 51 28" src="https://user-images.githubusercontent.com/30931733/40626471-0aacc726-62b9-11e8-8e7c-b5186b8776e7.png">

**Comment by join3r** [comment]
Try it with
sudo npm install -g --unsafe-perm homebridge-samsung-airconditioner

**Comment by szeldavid** [comment]
hello, thank you for the response.
It installed, although with a bunch of errors:
<img width="822" alt="kepernyofoto 2018-06-16 - 14 22 01" src="https://user-images.githubusercontent.com/30931733/41498631-0644de6c-7173-11e8-8c31-cfd87eef1454.png">

Now I'm trying to find the location of Server8889.py to run it. Do you know where it is?
Thank you

**Comment by join3r** [comment]
Right here :)
git clone https://github.com/cicciovo/homebridge-samsung-airconditioner.git

**Comment by szeldavid** [comment]
Sorry, I wasn't clear enough, I mean locally on the raspberry pi where is the Server8889.py located.
Or it does not get downloaded with this plugin and I have to download it separately?
Sorry for being a pain, and thank you!

**Comment by cicciovo** [comment]
Sorry for the late, what is the problem? Da you resolve it?

**Comment by szeldavid** [comment]
I don't know what to do after installation.
How can I run the Server8889.py ?
