### ISSUE TITLE
I can't get the ID Token...

### ISSUE THREAD

**Issue by serambca** [cicciovo/homebridge-samsung-airconditioner#7]
I launch the python Server8889.py and in the other terminal I launch the following command:

curl -k -H "Content-Type: application/json" -H "DeviceToken: xxxxxxxxxxx" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X POST https://192.168.1.72:8888/devicetoken/request

The IP address I change my own.

I get the following error:
   curl: (7) Failed to connect to 192.168.1.72 port 8888: Operation timed out

I verify that the IP Address is the correct. How I can solve it?

Thanks and regards

**Comment by cicciovo** [comment]
When you launch the command, do you turn on the AC?

**Comment by serambca** [comment]
@cicciovo ... of course...
I can do it a ping and control remotely with the app.

**Comment by cicciovo** [comment]
The port 8888 it s correct? Or your version is the 2878?

**Comment by serambca** [comment]
How I can know which version is it?

**Comment by stalkerj** [comment]
You need to scan ports on you AC ip with special software for port scanning

**Comment by serambca** [comment]
HI,

I just verified the ports open and only I see opened 2878.

PORT     STATE  SERVICE
2878/tcp open   aap
8888/tcp closed sun-answerbook

How I can use homebridge with this model?

**Comment by cicciovo** [comment]
You can’t use this plugin with the port 2878, you can try to update firmware of your AC

**Comment by serambca** [comment]
Hi cicciovo. !!

Thanks for your support!. Do you know how I can update the firmware? 
I tried to access the App of Smart Air of Samsung and don't detecte nothing. 

Thanks and regards,

**Comment by serambca** [comment]
Do you know when this script will work with the AC with port 2878?

Thanks and regards!

**Comment by stalkerj** [comment]
When someone can made do it)

**Comment by szeldavid** [comment]
Can someone make it to work with port 2878? I would pay to support it.

**Comment by getafe83** [comment]
> ¿Alguien puede llegar a trabajar con el puerto 2878? Pagaría para apoyarlo.

+1

**Comment by tkislan** [comment]
@cicciovo Did you encounter AC units that did not have either of those ports open?

```sh
~ # nmap -sS -p 2878,8888 192.168.1.11
Starting Nmap 7.70 ( https://nmap.org ) at 2019-01-27 18:25 UTC
Nmap scan report for 192.168.1.11
Host is up (0.053s latency).

PORT     STATE  SERVICE
2878/tcp closed aap
8888/tcp closed sun-answerbook
MAC Address: 70:2C:1F:5F:2A:C1 (Wisol)

Nmap done: 1 IP address (1 host up) scanned in 1.12 seconds
```

**Comment by cicciovo** [comment]
No, sorry, my 3 AC have the 8888 open...
