### ISSUE TITLE
Samsung A/C on port 2878

### ISSUE THREAD

**Issue by peros550** [cicciovo/homebridge-samsung-airconditioner#9]
Hey, I was very happy to find out this plugin and then I did a port scan on my A/C only to find out it works on 2878. 

Is there any luck for me? I am very willing to test your code on my A/C if I can help you somehow. 

Thanks in advance

**Comment by djsomi** [comment]
+1

**Comment by cicciovo** [comment]
Sorry, i’m working only for the version with port 8888.
You can try to update the firmware of your AC, but i don’t know how.

**Comment by bossco79** [comment]
+1

**Comment by peros550** [comment]
If you could let us know how we could help you on your project, we could all benefit and add Samsung A/C on port 2878 to the list of working devices. 

I searched your suggestion but didn't find anything in regards to firmware update.

**Comment by getafe83** [comment]
+1

**Comment by stalkerj** [comment]
+1

**Comment by SebastianOsinski** [comment]
Hi everyone! I managed to create working plugin for my Samsung AC working on 2878 port. It already supports turning on/off, setting temp and mode, reacting to changes from remote. There are still some problems with setting target temperature for heating mode but it should be solvable. As soon as I finish those fixes and create script for getting token, I’ll make I available and notify you here.

**Comment by stalkerj** [comment]
Waiting to test))) great news!

**Comment by robertodorta** [comment]
Great news!!!!

**Comment by peros550** [comment]
Thank you Sebastian! Looking forward to try your solution!

**Comment by djsomi** [comment]
Thanks Sebastian!!

**Comment by cicciovo** [comment]
👍🏻👍🏻💪🏼 Good work!

**Comment by SebastianOsinski** [comment]
Here it is: https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner enjoy! 
Please make PRs with your model numbers if this plugin works with them.

**Comment by djsomi** [comment]
Working fine, many-many thanks!
My Device: AR7000L (BETTER) AR12HSSDBWKNEU
​
